version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    open-pull-requests-limit: 5
    groups:
      Github Actions updates:
        applies-to: version-updates
        dependency-type: production
    schedule:
      # Check for updates to GitHub Actions every week
      day: "monday"
      time: "10:00"
      interval: "weekly"
  # Security updates - handled automatically by dependabot
  - package-ecosystem: "gomod"
    directory: "/"
    open-pull-requests-limit: 5
    groups:
      Go security updates:
        applies-to: security-updates
        patterns: ["*"]
    schedule:
      # Check for security updates more frequently
      interval: "daily"
