apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: elrond
  annotations:
    github.com/project-slug: mattermost/elrond
    backstage.io/adr-location: docs/adrs
spec:
  type: "service"
  system: "cloud-services"
  lifecycle: "production"
  owner: "cloud-sre"
