version: 2.1
executors:
  default:
    docker:
      - image: cimg/go:1.18.0

jobs:
  lint:
    executor:
      name: default
    steps:
      - checkout
      - run: make check-style

  test:
    executor:
      name: default
    steps:
      - checkout
      - run: make unittest

  push-docker-pr:
    executor:
      name: default
    steps:
    - checkout
    - setup_remote_docker
    - run: make build-image
    - run: ./scripts/push-image-pr.sh
    - run:
        name: Re-run Docker Push if fail
        command: |
            sleep 20
            ./scripts/push-image-pr.sh
        when: on_fail

  push-docker:
    executor:
      name: default
    steps:
    - checkout
    - setup_remote_docker
    - run: make build-image
    - run: ./scripts/push-image.sh
    - run:
        name: Re-run Docker Push if fail
        command: |
            sleep 20
            ./scripts/push-image.sh
        when: on_fail

workflows:
  version: 2
  pr-build:
    jobs:
    - lint
    - test
    - push-docker-pr:
        context: matterbuild-docker
        requires:
        - lint
        - test
  main-build:
    jobs:
    - lint:
        filters:
          branches:
            only:
            - main
    - test:
        filters:
          branches:
            only:
            - main
    - push-docker:
          context: matterbuild-docker
          requires:
          - lint
          - test
          filters:
            branches:
              only:
              - main
  tag-builds:
    jobs:
    - lint:
        filters:
          tags:
            only: /^v.*/
          branches:
            ignore: /.*/
    - test:
        filters:
          tags:
            only: /^v.*/
          branches:
            ignore: /.*/
    - push-docker:
        context: matterbuild-docker
        requires:
        - lint
        - test
        filters:
          tags:
            only: /^v.*/
          branches:
            ignore: /.*/
