version: 2.1
executors:
  default:
    docker:
      - image: cimg/go:1.18.0

jobs:
  lint:
    executor:
      name: default
    steps:
      - checkout
      - run: make check-style

  test:
    executor:
      name: default
    steps:
      - checkout
      - run: make unittest

workflows:
  version: 2
  pr-build:
    jobs:
    - lint
    - test
