---
name: 'docker-prepare'
description: 'Install docker requirements'

runs:
  using: 'composite'
  steps:
  - uses: docker/setup-buildx-action@v2
    with:
      version: v0.7.1
  - shell: bash
    run: |
      docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
      docker run --privileged --rm tonistiigi/binfmt --install arm64
