---
name: 'docker-prepare'
description: 'Install docker requirements'

runs:
  using: 'composite'
  steps:
  - shell: bash
    run: |
      mkdir -vp ~/.docker/cli-plugins/
      curl --silent -L "https://github.com/docker/buildx/releases/download/v0.7.1/buildx-v0.7.1.linux-amd64" > ~/.docker/cli-plugins/docker-buildx
      chmod a+x ~/.docker/cli-plugins/docker-buildx
      docker buildx version
      apt-get update && apt-get install -y binfmt-support qemu-user-static
      docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
      docker run --privileged --rm tonistiigi/binfmt --install arm64
      docker context create buildcontext
      docker buildx create buildcontext --use
