---
on:
  workflow_call:
    inputs:
      is_pr:
        required: true
        type: boolean
    secrets:
      dockerhub_username:
        required: true
      dockerhub_token:
        required: true

env:
  DOCKER_USERNAME: "${{ secrets.dockerhub_username }}"
  DOCKER_PASSWORD: "${{ secrets.dockerhub_token }}"

jobs:
  docker-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: docker/setup-buildx-action@v3
      with:
        version: v0.7.1
    - run: |
        find ~/.docker
        docker buildx version
        dpkg --list binfmt-support qemu-user-static || :
        apt-get update && apt-get install -y binfmt-support qemu-user-static
        docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
        docker run --privileged --rm tonistiigi/binfmt --install arm64
        docker context create buildcontext
        docker buildx create buildcontext --use
    - run: "make push-image-pr"
      if: "${{ inputs.is_pr }}"
    - run: "make push-image"
      if: "${{ !inputs.is_pr }}"
