---
name: test
on:
  workflow_call:

jobs:
  check-style:
    runs-on: ubuntu-latest
    env:
      GOFLAGS: "-buildvcs=false"
    container:
      image: golang:1.24.3-bookworm
    steps:
    - name: ci/checkout-repo
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
    - name: ci/fix-git-permissions
      run: git config --global --add safe.directory "${GITHUB_WORKSPACE}"
    - name: ci/cache-gopath
      uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809 # v4.2.4
      with:
        key: go-mod-v1-${{ hashFiles('go.sum') }}
        path: /go
      if: "${{ !env.ACT }}"
    - name: ci/check-code-style
      run: make check-style

  test:
    runs-on: ubuntu-latest
    container:
      image: golang:1.24.3-bookworm
    steps:
    - name: ci/checkout-repo
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
    - name: ci/fix-git-permissions
      run: git config --global --add safe.directory "${GITHUB_WORKSPACE}"
    - name: ci/cache-gopath
      uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809 # v4.2.4
      with:
        key: go-mod-v1-${{ hashFiles('go.sum') }}
        path: /go
      if: "${{ !env.ACT }}"
    - name: ci/unit-test
      run: make unittest
