---
name: test
on:
  workflow_call:

jobs:
  check-style:
    runs-on: ubuntu-latest
    env:
      GOFLAGS: "-buildvcs=false"
    container:
      image: golang:1.23.2-bookworm
    steps:
    - name: ci/checkout-repo
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - name: ci/cache-gopath
      uses: actions/cache@d4323d4df104b026a6aa633fdb11d772146be0bf # v4.2.2
      with:
        key: go-mod-v1-${{ hashFiles('go.sum') }}
        path: /go
      if: "${{ !env.ACT }}"
    - name: ci/check-code-style
      run: make check-style

  test:
    runs-on: ubuntu-latest
    container:
      image: golang:1.23.2-bookworm
    steps:
    - name: ci/checkout-repo
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - name: ci/cache-gopath
      uses: actions/cache@d4323d4df104b026a6aa633fdb11d772146be0bf # v4.2.2
      with:
        key: go-mod-v1-${{ hashFiles('go.sum') }}
        path: /go
      if: "${{ !env.ACT }}"
    - name: ci/unit-test
      run: make unittest
