---
on:
  push:
    branches: ["*"]

jobs:
  test:
    uses: ./.github/workflows/.test.yml
  push-docker:
    uses: ./.github/workflows/.docker-push.yml
    with:
      is_pr: "${{ github.ref != 'refs/heads/main' }}"
    secrets:
      dockerhub_username: "${{ secrets.DOCKERHUB_USERNAME }}"
      dockerhub_token: "${{ secrets.DOCKERHUB_TOKEN }}"
    needs: [test]
