---
on:
  push:
    branches:
    - main

jobs:
  test:
    uses: ./.github/workflows/.test.yml
  push-docker:
    uses: ./.github/workflows/.docker-push.yml
    with:
      is_pr: false
    secrets:
      dockerhub_username: "${{ secrets.DOCKERHUB_USERNAME }}"
      dockerhub_token: "${{ secrets.DOCKERHUB_TOKEN }}"
    needs: [test]
