---
name: release
on:
  push:
    tags:
    - v[0-9]+.[0-9]+.[0-9]+*

jobs:
  test:
    uses: ./.github/workflows/.test.yml
  push-docker:
    uses: ./.github/workflows/.docker-push.yml
    with:
      is_pr: false
    secrets: inherit
    needs: [test]
  release:
    runs-on: ubuntu-latest
    container:
      image: golang:1.18.0-bullseye
    env:
      GITHUB_TOKEN: "${{ secrets.GH_TOKEN }}"
    steps:
    - name: ci/checkout-repo
      uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
    - name: ci/install-release-dependencies
      run: make deps
    - name: ci/publish-release
      run: make release
    needs: [push-docker]
