---
on:
  workflow_call:

jobs:
  check-style:
    runs-on: ubuntu-latest
    container:
      image: golang:1.18.0-bullseye
    steps:
    - uses: actions/checkout@v3
    - uses: actions/cache@v3
      with:
        key: go-mod-v1-${{ hashFiles('go.sum') }}
        path: /go
      if: "${{ !env.ACT }}"
    - run: make check-style

  test:
    runs-on: ubuntu-latest
    container:
      image: golang:1.18.0-bullseye
    steps:
    - uses: actions/checkout@v3
    - uses: actions/cache@v3
      with:
        key: go-mod-v1-${{ hashFiles('go.sum') }}
        path: /go
      if: "${{ !env.ACT }}"
    - run: make unittest
